# Generated by Django 4.2.9 on 2024-05-29 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('otp', models.PositiveIntegerField(default=0)),
                ('otp_status', models.BooleanField(default=False)),
                ('otp_count', models.PositiveIntegerField(default=0)),
                ('profile', models.ImageField(upload_to='ProfileImage/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='family_bios',
            fields=[
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_begin', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=10)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('family_last_name', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogoColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogoSvg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='Logo/')),
                ('svg_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogoSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('symbol_name', models.CharField(default='', max_length=50)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='Logo_Symbol/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dir', models.CharField(blank=True, max_length=255, null=True)),
                ('family_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_duplicate', models.CharField(blank=True, max_length=255, null=True)),
                ('font_style', models.IntegerField(blank=True, choices=[(0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (3, 'Value 3'), (4, 'Value 4'), (5, 'Value 5'), (6, 'Value 6'), (7, 'Value 7')], null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedSvg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='Related_Logo/')),
                ('svg_code', models.TextField(blank=True, null=True)),
                ('logo_svg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.logosvg')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.logosymbol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhitelistToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.TextField()),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisionStatements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('logo', models.ImageField(upload_to='User_Logo/')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.familydetails')),
                ('logo_svg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.relatedsvg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('note', models.TextField(default='')),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='parent_members',
            fields=[
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('relation', models.CharField(blank=True, choices=[('mom', 'Mom'), ('dad', 'Dad'), ('step-mom', 'Step-Mom'), ('step-dad', 'Step-Dad'), ('grandma', 'Grandma'), ('grandpa', 'Grandpa'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=50, null=True)),
                ('other_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='images/dummy.png', null=True, upload_to='images/')),
                ('favourite_food', models.CharField(blank=True, max_length=255, null=True)),
                ('other_favourite_food', models.CharField(blank=True, max_length=255, null=True)),
                ('favourite_holiday', models.CharField(blank=True, max_length=255, null=True)),
                ('other_favourite_holiday', models.CharField(blank=True, max_length=255, null=True)),
                ('afraid_of', models.CharField(blank=True, max_length=255, null=True)),
                ('other_afraid_of', models.CharField(blank=True, max_length=255, null=True)),
                ('other_favourite_quote', models.CharField(blank=True, max_length=255, null=True)),
                ('favourite_quote', models.CharField(blank=True, max_length=255, null=True)),
                ('is_quote', models.IntegerField(default=0)),
                ('family_bios_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.family_bios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='other_members',
            fields=[
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter'), ('other', 'Other')], max_length=50)),
                ('other_relation', models.CharField(default='', max_length=255)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('birth_city', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('best_attribute', models.CharField(default='', max_length=255)),
                ('second_best_attribute', models.CharField(default='', max_length=255)),
                ('dob', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('favourite_food', models.CharField(default='', max_length=255)),
                ('other_favourite_food', models.CharField(default='', max_length=255)),
                ('other_favourite_quote', models.CharField(default='', max_length=255)),
                ('other_best_attribute', models.CharField(default='', max_length=255)),
                ('is_quote', models.IntegerField(default=0)),
                ('family_bios_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.family_bios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissionStatements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('admin_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.adminsubscription')),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auth')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='logosvg',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.logosymbol'),
        ),
        migrations.CreateModel(
            name='IntroductionPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('beginning_letter', models.CharField(blank=True, default='Dear Family', max_length=100, null=True)),
                ('tone_used', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('characters_list', models.TextField(blank=True, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMediaAgreements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('statement_one', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_two', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_three', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_four', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_five', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_six', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_seven', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_eight', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_nine', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_ten', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyConstitutions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('note', models.TextField(default='')),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='family_bios',
            name='pdf_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf'),
        ),
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sentence', models.TextField(blank=True, max_length=255, null=True)),
                ('family_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_duplicate', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('sub_title', models.TextField(blank=True, max_length=255, null=True)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('value_one', models.CharField(blank=True, max_length=255, null=True)),
                ('value_two', models.CharField(blank=True, max_length=255, null=True)),
                ('value_three', models.CharField(blank=True, max_length=255, null=True)),
                ('value_four', models.CharField(blank=True, max_length=255, null=True)),
                ('value_five', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeOfConducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('statement_one', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_two', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_three', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_four', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_five', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_six', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_seven', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_eight', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_nine', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_ten', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_eleven', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_twelve', models.CharField(blank=True, max_length=255, null=True)),
                ('statement_thirteen', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finished', models.IntegerField(choices=[(0, '0'), (1, '1')], default=0)),
                ('pdf_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auth',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.AddField(
            model_name='adminsubscription',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auth'),
        ),
        migrations.AddField(
            model_name='adminsubscription',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subscription'),
        ),
    ]
